### ISSUE TITLE
git clone失败

### ISSUE THREAD

**Issue by Agnes4m** [CCYellowStar2/nonebot-plugin-aising#1]
![image](https://github.com/CCYellowStar2/nonebot-plugin-aising/assets/70925546/13ce844a-6b4f-42e2-95ab-374086877e5d)

**Comment by CCYellowStar2** [comment]
> ![image](https://private-user-images.githubusercontent.com/70925546/336273257-13ce844a-6b4f-42e2-95ab-374086877e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODc1NDksIm5iZiI6MTcxNzQ4NzI0OSwicGF0aCI6Ii83MDkyNTU0Ni8zMzYyNzMyNTctMTNjZTg0NGEtNmI0Zi00MmUyLTk1YWItMzc0MDg2ODc3ZTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA3NDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YTY4MTUwYjhjM2RmYzk1OTU2NjU4ZmQ0NjczNDIzY2E3YjYyMDk2MGJlM2ExM2FlYTI4NDdhODNmM2JjNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.07q49Gq-sZmo0Yi5y5ZzHyHq1dpVRgCaSqjndSXbNIM)
 使用git config --global http.proxy "localhost:10809"在cmd设置你使用的代理
