### ISSUE TITLE
程序在用cpu跑，用bv号唱歌报错

### ISSUE THREAD

**Issue by niucattle** [CCYellowStar2/nonebot-plugin-aising#3]
![c86bf67ef02cda7f8fd649dbf8bb2d01](https://github.com/CCYellowStar2/nonebot-plugin-aising/assets/118875129/0a7e464d-a87b-48aa-b9ac-f3d9a9e4b21a)
但我显卡确实是在工作的  
这正常吗
.
![02d6785fb49f63d171bbb9614aba0eb7](https://github.com/CCYellowStar2/nonebot-plugin-aising/assets/118875129/6b3a5729-16b6-46f2-83c0-2e25f160e745)

**Comment by CCYellowStar2** [comment]
正常的，是再用你显卡

**Comment by niucattle** [comment]
> 正常的，是再用你显卡

还有这种情况
![image](https://github.com/CCYellowStar2/nonebot-plugin-aising/assets/118875129/cf94395a-e3b7-45c6-a47f-7e84da7539f6)
![image](https://github.com/CCYellowStar2/nonebot-plugin-aising/assets/118875129/b8359cf5-703d-4f49-bafc-d3d9c83e4b61)
生成时有时无的

**Comment by niucattle** [comment]
![image](https://github.com/CCYellowStar2/nonebot-plugin-aising/assets/118875129/18f6b1ae-003c-4af9-8467-80dab722de21)

**Comment by CCYellowStar2** [comment]
好像有些视频会这样

**Comment by niucattle** [comment]
> 好像有些视频会这样

好像不是有些视频 我现在已经百分百触发这个了 试了好几个视频

**Comment by CCYellowStar2** [comment]
> > 好像有些视频会这样
> 
> 好像不是有些视频 我现在已经百分百触发这个了 试了好几个视频

两边输入的都是不同的吗，让谁唱什么是两个视频

**Comment by niucattle** [comment]
> > > 好像有些视频会这样
> > 
> > 
> > 好像不是有些视频 我现在已经百分百触发这个了 试了好几个视频
> 
> 两边输入的都是不同的吗，让谁唱什么是两个视频

是两个  一个是角色语音视频 一个是歌曲

**Comment by CCYellowStar2** [comment]
> > > > 好像有些视频会这样
> > > 
> > > 
> > > 好像不是有些视频 我现在已经百分百触发这个了 试了好几个视频
> > 
> > 
> > 两边输入的都是不同的吗，让谁唱什么是两个视频
> 
> 是两个 一个是角色语音视频 一个是歌曲

就是尝试不同的组合也这样吗

**Comment by niucattle** [comment]
> > > > > 好像有些视频会这样
> > > > 
> > > > 
> > > > 好像不是有些视频 我现在已经百分百触发这个了 试了好几个视频
> > > 
> > > 
> > > 两边输入的都是不同的吗，让谁唱什么是两个视频
> > 
> > 
> > 是两个 一个是角色语音视频 一个是歌曲
> 
> 就是尝试不同的组合也这样吗

是的 但我直接在后端运行是能跑的

**Comment by CCYellowStar2** [comment]
> > > > > > 好像有些视频会这样
> > > > > 
> > > > > 
> > > > > 好像不是有些视频 我现在已经百分百触发这个了 试了好几个视频
> > > > 
> > > > 
> > > > 两边输入的都是不同的吗，让谁唱什么是两个视频
> > > 
> > > 
> > > 是两个 一个是角色语音视频 一个是歌曲
> > 
> > 
> > 就是尝试不同的组合也这样吗
> 
> 是的 但我直接在后端运行是能跑的

后端直接跑没有出现过吗

**Comment by CCYellowStar2** [comment]
但这不太合理，这就是后端的报错

**Comment by niucattle** [comment]
> 但这不太合理，这就是后端的报错

完全没有

**Comment by CCYellowStar2** [comment]
> > 但这不太合理，这就是后端的报错
> 
> 完全没有
那你在bot跑是报错一次又不报错一次吗

**Comment by niucattle** [comment]
> > > 但这不太合理，这就是后端的报错
> > 
> > 
> > 完全没有
> > 那你在bot跑是报错一次又不报错一次吗

就刚开始试的第一次成功了 后来就再也没成功过了

**Comment by CCYellowStar2** [comment]
后端一直是那个报错吗

**Comment by niucattle** [comment]
> 后端一直是那个报错吗

一直是一样的报错

**Comment by CCYellowStar2** [comment]
重启bot会恢复吗

**Comment by niucattle** [comment]
> 重启bot会恢复吗

我试试

**Comment by niucattle** [comment]
> 重启bot会恢复吗

没有效果

**Comment by niucattle** [comment]
让BV1L8411u7sA唱BV1os411g7w4这个指令能稳定跑出来 其他不行

**Comment by CCYellowStar2** [comment]
> 让BV1L8411u7sA唱BV1os411g7w4这个指令能稳定跑出来 其他不行

其他不行是不是不是bv的都不行

**Comment by niucattle** [comment]
> > 让BV1L8411u7sA唱BV1os411g7w4这个指令能稳定跑出来 其他不行
> 
> 其他不行是不是不是bv的都不行

我多试试先

**Comment by CCYellowStar2** [comment]
> > > 让BV1L8411u7sA唱BV1os411g7w4这个指令能稳定跑出来 其他不行
> > 
> > 
> > 其他不行是不是不是bv的都不行
> 
> 我多试试先

主要我这都没出现过

**Comment by niucattle** [comment]
> > > > 让BV1L8411u7sA唱BV1os411g7w4这个指令能稳定跑出来 其他不行
> > > 
> > > 
> > > 其他不行是不是不是bv的都不行
> > 
> > 
> > 我多试试先
> 
> 主要我这都没出现过
似乎 音色来源的视频 过长  就会这样    你试试让BV11V411J7Lz这个视频里的音色去唱歌  我这百分百报错  但我去后端用是没问题

**Comment by CCYellowStar2** [comment]
> > > > > 让BV1L8411u7sA唱BV1os411g7w4这个指令能稳定跑出来 其他不行
> > > > 
> > > > 
> > > > 其他不行是不是不是bv的都不行
> > > 
> > > 
> > > 我多试试先
> > 
> > 
> > 主要我这都没出现过
> > 似乎 音色来源的视频 过长  就会这样    你试试让BV11V411J7Lz这个视频里的音色去唱歌  我这百分百报错  但我去后端用是没问题

所以我才问你是特定视频还是所有视频，你报错的都有哪些视频

**Comment by niucattle** [comment]
> > > > > > 让BV1L8411u7sA唱BV1os411g7w4这个指令能稳定跑出来 其他不行
> > > > > 
> > > > > 
> > > > > 其他不行是不是不是bv的都不行
> > > > 
> > > > 
> > > > 我多试试先
> > > 
> > > 
> > > 主要我这都没出现过
> > > 似乎 音色来源的视频 过长  就会这样    你试试让BV11V411J7Lz这个视频里的音色去唱歌  我这百分百报错  但我去后端用是没问题
> 
> 所以我才问你是特定视频还是所有视频，你报错的都有哪些视频
让BV1pZ4y1F7BM唱BV1MR4y1V7Hr   
让BV1a4411H7Uo唱BV1MR4y1V7Hr
让BV1a4411H7Uo唱Young and Beautiful
让BV1a4411H7Uo唱BV1KT411F7LB
让BV1a4411H7Uo唱The Saltwater Room
让BV1md4y1y7Gk唱Young And Beautiful
让BV11V411J7Lz唱BV1md4y1y7Gk

**Comment by CCYellowStar2** [comment]
> > > > > > > 让BV1L8411u7sA唱BV1os411g7w4这个指令能稳定跑出来 其他不行
> > > > > > 
> > > > > > 
> > > > > > 其他不行是不是不是bv的都不行
> > > > > 
> > > > > 
> > > > > 我多试试先
> > > > 
> > > > 
> > > > 主要我这都没出现过
> > > > 似乎 音色来源的视频 过长  就会这样    你试试让BV11V411J7Lz这个视频里的音色去唱歌  我这百分百报错  但我去后端用是没问题
> > 
> > 
> > 所以我才问你是特定视频还是所有视频，你报错的都有哪些视频
> > 让BV1pZ4y1F7BM唱BV1MR4y1V7Hr
> > 让BV1a4411H7Uo唱BV1MR4y1V7Hr
> > 让BV1a4411H7Uo唱Young and Beautiful
> > 让BV1a4411H7Uo唱BV1KT411F7LB
> > 让BV1a4411H7Uo唱The Saltwater Room
> > 让BV1md4y1y7Gk唱Young And Beautiful
> > 让BV11V411J7Lz唱BV1md4y1y7Gk

你这些我也会报错，好像全是明日方舟的

**Comment by niucattle** [comment]
> > > > > > > > 让BV1L8411u7sA唱BV1os411g7w4这个指令能稳定跑出来 其他不行
> > > > > > > 
> > > > > > > 
> > > > > > > 其他不行是不是不是bv的都不行
> > > > > > 
> > > > > > 
> > > > > > 我多试试先
> > > > > 
> > > > > 
> > > > > 主要我这都没出现过
> > > > > 似乎 音色来源的视频 过长  就会这样    你试试让BV11V411J7Lz这个视频里的音色去唱歌  我这百分百报错  但我去后端用是没问题
> > > 
> > > 
> > > 所以我才问你是特定视频还是所有视频，你报错的都有哪些视频
> > > 让BV1pZ4y1F7BM唱BV1MR4y1V7Hr
> > > 让BV1a4411H7Uo唱BV1MR4y1V7Hr
> > > 让BV1a4411H7Uo唱Young and Beautiful
> > > 让BV1a4411H7Uo唱BV1KT411F7LB
> > > 让BV1a4411H7Uo唱The Saltwater Room
> > > 让BV1md4y1y7Gk唱Young And Beautiful
> > > 让BV11V411J7Lz唱BV1md4y1y7Gk
> 
> 你这些我也会报错，好像全是明日方舟的

但这些在后端跑确实是没问题

**Comment by CCYellowStar2** [comment]
> > > > > > > > > 让BV1L8411u7sA唱BV1os411g7w4这个指令能稳定跑出来 其他不行
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 其他不行是不是不是bv的都不行
> > > > > > > 
> > > > > > > 
> > > > > > > 我多试试先
> > > > > > 
> > > > > > 
> > > > > > 主要我这都没出现过
> > > > > > 似乎 音色来源的视频 过长  就会这样    你试试让BV11V411J7Lz这个视频里的音色去唱歌  我这百分百报错  但我去后端用是没问题
> > > > 
> > > > 
> > > > 所以我才问你是特定视频还是所有视频，你报错的都有哪些视频
> > > > 让BV1pZ4y1F7BM唱BV1MR4y1V7Hr
> > > > 让BV1a4411H7Uo唱BV1MR4y1V7Hr
> > > > 让BV1a4411H7Uo唱Young and Beautiful
> > > > 让BV1a4411H7Uo唱BV1KT411F7LB
> > > > 让BV1a4411H7Uo唱The Saltwater Room
> > > > 让BV1md4y1y7Gk唱Young And Beautiful
> > > > 让BV11V411J7Lz唱BV1md4y1y7Gk
> > 
> > 
> > 你这些我也会报错，好像全是明日方舟的
> 
> 但这些在后端跑确实是没问题

我重开一次后端好像没事了

**Comment by niucattle** [comment]
> > > > > > > > > > 让BV1L8411u7sA唱BV1os411g7w4这个指令能稳定跑出来 其他不行
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 其他不行是不是不是bv的都不行
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我多试试先
> > > > > > > 
> > > > > > > 
> > > > > > > 主要我这都没出现过
> > > > > > > 似乎 音色来源的视频 过长  就会这样    你试试让BV11V411J7Lz这个视频里的音色去唱歌  我这百分百报错  但我去后端用是没问题
> > > > > 
> > > > > 
> > > > > 所以我才问你是特定视频还是所有视频，你报错的都有哪些视频
> > > > > 让BV1pZ4y1F7BM唱BV1MR4y1V7Hr
> > > > > 让BV1a4411H7Uo唱BV1MR4y1V7Hr
> > > > > 让BV1a4411H7Uo唱Young and Beautiful
> > > > > 让BV1a4411H7Uo唱BV1KT411F7LB
> > > > > 让BV1a4411H7Uo唱The Saltwater Room
> > > > > 让BV1md4y1y7Gk唱Young And Beautiful
> > > > > 让BV11V411J7Lz唱BV1md4y1y7Gk
> > > 
> > > 
> > > 你这些我也会报错，好像全是明日方舟的
> > 
> > 
> > 但这些在后端跑确实是没问题
> 
> 我重开一次后端好像没事了

你多跑两个 就又不行了

**Comment by CCYellowStar2** [comment]
我发现问题了，我是傻逼，让谁唱都加ai两个字

**Comment by niucattle** [comment]
> 我发现问题了，我是傻逼，让谁唱都加ai两个字

纳尼

**Comment by CCYellowStar2** [comment]
我是在程序里写的判断如果唱的没有加ai两个字我就在前面加ai，但忘了判断bv号的情况

**Comment by CCYellowStar2** [comment]
你更新下

**Comment by niucattle** [comment]
> 你更新下

解决了ｂ(￣▽￣)ｄ
