### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lin6953** [CCYellowStar2/nonebot-plugin-aising#4]
适配器llonebot
问题:发不出语音，后端已经生成出来文件了

![Image_1717947955161.jpg](https://github.com/CCYellowStar2/nonebot-plugin-aising/assets/107689301/c13ce958-0ff5-4956-8e68-b08e487a71e2)

上面已经没有报错了，就只有这一条消息的返回

**Comment by CCYellowStar2** [comment]
没试过llonebot，你有其他语音插件吗

**Comment by CCYellowStar2** [comment]
你看看你的C:\Users\Administrator\AppData\Local\Temp\2\gradio里有没有文件

**Comment by linya72** [comment]
> 文件

有文件，大佬能适配一下llonebot吗？

**Comment by lin6953** [comment]
> 你看看你的C:\Users\Administrator\AppData\Local\Temp\2\gradio里有没有文件

有文件，大佬能适配一下llonebot吗？

**Comment by CCYellowStar2** [comment]
> > 你看看你的C:\Users\Administrator\AppData\Local\Temp\2\gradio里有没有文件
> 
> 有文件，大佬能适配一下llonebot吗？

那你有在用其他能发出语音的插件吗

**Comment by Well2333** [comment]
经测试，llob可以稳定复现音频无法发出，将源代码中此行

https://github.com/CCYellowStar2/nonebot-plugin-aising/blob/master/nonebot_plugin_aising/__init__.py#L148

`MessageSegment.record(file_uri)` 修改为 `MessageSegment.record(Path(location).read_bytes())`

即可解决问题
