### ISSUE TITLE
生成一次之后重启了一下机器，后端就寄了

### ISSUE THREAD

**Issue by memoriass** [CCYellowStar2/nonebot-plugin-aising#6]
![image](https://github.com/CCYellowStar2/nonebot-plugin-aising/assets/108792311/7352470f-2ceb-4d1c-a0fd-23d93bcf82bc)
![image](https://github.com/CCYellowStar2/nonebot-plugin-aising/assets/108792311/a67308f2-cb85-4ba4-8c0b-b2a82ab106d7)
提示好像是这个文件找不到还是权限不够，是需要给文件夹给修改权限么，我把后端整个文件夹都给了777权限也不行 启动也是用的sudo启动的py文件

**Comment by CCYellowStar2** [comment]
有用的报错应该还在上面，上面应该还有出错的导致没生成成功

**Comment by memoriass** [comment]
[log.txt](https://github.com/user-attachments/files/15949557/log.txt)
佬  zhe这是完整日志  我排查了一下之前正常渲染是纯cpu模式  我直通了一张显卡加速后就跑不起来了

**Comment by CCYellowStar2** [comment]
我也没试过Linux这种的，我看报错好像有提到cuda没找到之类的

**Comment by CCYellowStar2** [comment]
反正我windows手动装cuda才能用显卡

**Comment by memoriass** [comment]
佬  我摇人解决了  确实是cuda的问题  不过这个只能生成1分钟么  不能加长点么  大概一分半左右可以放完半首歌  一分钟感觉刚唱上去就没了

**Comment by CCYellowStar2** [comment]
> 佬  我摇人解决了  确实是cuda的问题  不过这个只能生成1分钟么  不能加长点么  大概一分半左右可以放完半首歌  一分钟感觉刚唱上去就没了

我试过超过一分多他就乱唱了，唱飘了，一分半可能是极限，我本来也想加自定义时间的，但就是试了发现他长了会唱飘就没加
